# Generated by Django 5.2.3 on 2026-01-20 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atvs', '0002_alter_atvs_options_alter_atvs_body_alter_atvs_name_and_more'),
        ('cars', '0002_alter_cars_options_alter_cars_body_and_more'),
        ('mopeds', '0002_alter_moped_options_alter_moped_body_and_more'),
        ('motocycles', '0002_alter_motocycles_options_alter_motocycles_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('common', 'Звичайний'), ('rare', 'Рідкісний'), ('epic', 'Епічний'), ('legendary', 'Легендарний')], default='common', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('atv', 'ATV'), ('moped', 'Moped'), ('motocycle', 'Motocycle')], max_length=20)),
                ('probability', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atvs.atvs')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cases.case')),
                ('moped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopeds.moped')),
                ('motocycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motocycles.motocycles')),
            ],
            options={
                'verbose_name_plural': 'Case Rewards',
            },
        ),
        migrations.CreateModel(
            name='OpenedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cases', to='cases.case')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casereward')),
            ],
            options={
                'verbose_name_plural': 'Opened Cases',
                'ordering': ['-opened_at'],
            },
        ),
    ]
