# Generated by Django 5.2.3 on 2025-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('body', models.CharField()),
                ('motor', models.FloatField()),
                ('starter', models.BooleanField()),
            ],
        ),
    ]
