# Generated by Django 5.2.3 on 2025-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motocycles',
            options={'verbose_name_plural': 'Motocycles'},
        ),
        migrations.AlterField(
            model_name='motocycles',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motocycles',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motocycles',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
