# Generated by Django 5.2.3 on 2026-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocycles', '0002_alter_motocycles_options_alter_motocycles_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocycles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motocycles/'),
        ),
    ]
