# Generated by Django 5.2.3 on 2026-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atvs', '0002_alter_atvs_options_alter_atvs_body_alter_atvs_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atvs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='atvs/'),
        ),
    ]
