# Generated by Django 5.2.3 on 2025-12-21 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atvs', '0001_initial'),
        ('cars', '0001_initial'),
        ('mopeds', '0001_initial'),
        ('motocycles', '0002_alter_motocycles_options_alter_motocycles_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Garage', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Garages',
            },
        ),
        migrations.CreateModel(
            name='GarageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('atv', 'ATV'), ('moped', 'Moped'), ('motocycle', 'Motocycle')], max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('atv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atvs.atvs')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='garage.garage')),
                ('moped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mopeds.moped')),
                ('motocycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motocycles.motocycles')),
            ],
            options={
                'verbose_name_plural': 'Garage Items',
            },
        ),
    ]
