# Generated by Django 5.2.3 on 2026-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gear_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
