# Generated by Django 5.2.3 on 2026-01-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mopeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moped',
            options={'verbose_name_plural': 'Mopeds'},
        ),
        migrations.AlterField(
            model_name='moped',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moped',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moped',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
